export const continents = [
  {
    id: 'europe',
    countries: [
      { code: 'al', name: { en: 'Albania', es: 'Albania', de: 'Albanien', pl: 'Albania', ru: 'Албания', uk: 'Албанія', bg: 'Албания', ro: 'Albania', hu: 'Albánia', sk: 'Albánsko' } },
      { code: 'ad', name: { en: 'Andorra', es: 'Andorra', de: 'Andorra', pl: 'Andora', ru: 'Андорра', uk: 'Андорра', bg: 'Андора', ro: 'Andorra', hu: 'Andorra', sk: 'Andorra' } },
      { code: 'at', name: { en: 'Austria', es: 'Austria', de: 'Österreich', pl: 'Austria', ru: 'Австрия', uk: 'Австрія', bg: 'Австрия', ro: 'Austria', hu: 'Ausztria', sk: 'Rakúsko' } },
      { code: 'by', name: { en: 'Belarus', es: 'Bielorrusia', de: 'Belarus', pl: 'Białoruś', ru: 'Беларусь', uk: 'Білорусь', bg: 'Беларус', ro: 'Belarus', hu: 'Fehéroroszország', sk: 'Bielorusko' } },
      { code: 'be', name: { en: 'Belgium', es: 'Bélgica', de: 'Belgien', pl: 'Belgia', ru: 'Бельгия', uk: 'Бельгія', bg: 'Белгия', ro: 'Belgia', hu: 'Belgium', sk: 'Belgicko' } },
      { code: 'ba', name: { en: 'Bosnia and Herzegovina', es: 'Bosnia y Herzegovina', de: 'Bosnien und Herzegowina', pl: 'Bośnia i Hercegowina', ru: 'Босния и Герцеговина', uk: 'Боснія і Герцеговина', bg: 'Босна и Херцеговина', ro: 'Bosnia și Herțegovina', hu: 'Bosznia-Hercegovina', sk: 'Bosna a Hercegovina' } },
      { code: 'bg', name: { en: 'Bulgaria', es: 'Bulgaria', de: 'Bulgarien', pl: 'Bułgaria', ru: 'Болгария', uk: 'Болгарія', bg: 'България', ro: 'Bulgaria', hu: 'Bulgária', sk: 'Bulharsko' } },
      { code: 'hr', name: { en: 'Croatia', es: 'Croacia', de: 'Kroatien', pl: 'Chorwacja', ru: 'Хорватия', uk: 'Хорватія', bg: 'Хърватия', ro: 'Croația', hu: 'Horvátország', sk: 'Chorvátsko' } },
      { code: 'cy', name: { en: 'Cyprus', es: 'Chipre', de: 'Zypern', pl: 'Cypr', ru: 'Кипр', uk: 'Кіпр', bg: 'Кипър', ro: 'Cipru', hu: 'Ciprus', sk: 'Cyprus' } },
      { code: 'cz', name: { en: 'Czech Republic', es: 'República Checa', de: 'Tschechien', pl: 'Czechy', ru: 'Чехия', uk: 'Чехія', bg: 'Чехия', ro: 'Cehia', hu: 'Csehország', sk: 'Česko' } },
      { code: 'dk', name: { en: 'Denmark', es: 'Dinamarca', de: 'Dänemark', pl: 'Dania', ru: 'Дания', uk: 'Данія', bg: 'Дания', ro: 'Danemarca', hu: 'Dánia', sk: 'Dánsko' } },
      { code: 'ee', name: { en: 'Estonia', es: 'Estonia', de: 'Estland', pl: 'Estonia', ru: 'Эстония', uk: 'Естонія', bg: 'Естония', ro: 'Estonia', hu: 'Észtország', sk: 'Estónsko' } },
      { code: 'fi', name: { en: 'Finland', es: 'Finlandia', de: 'Finnland', pl: 'Finlandia', ru: 'Финляндия', uk: 'Фінляндія', bg: 'Финландия', ro: 'Finlanda', hu: 'Finnország', sk: 'Fínsko' } },
      { code: 'fr', name: { en: 'France', es: 'Francia', de: 'Frankreich', pl: 'Francja', ru: 'Франция', uk: 'Франція', bg: 'Франция', ro: 'Franța', hu: 'Franciaország', sk: 'Francúzsko' } },
      { code: 'de', name: { en: 'Germany', es: 'Alemania', de: 'Deutschland', pl: 'Niemcy', ru: 'Германия', uk: 'Німеччина', bg: 'Германия', ro: 'Germania', hu: 'Németország', sk: 'Nemecko' } },
      { code: 'gr', name: { en: 'Greece', es: 'Grecia', de: 'Griechenland', pl: 'Grecja', ru: 'Греция', uk: 'Греція', bg: 'Гърция', ro: 'Grecia', hu: 'Görögország', sk: 'Grécko' } },
      { code: 'hu', name: { en: 'Hungary', es: 'Hungría', de: 'Ungarn', pl: 'Węgry', ru: 'Венгрия', uk: 'Угорщина', bg: 'Унгария', ro: 'Ungaria', hu: 'Magyarország', sk: 'Maďarsko' } },
      { code: 'is', name: { en: 'Iceland', es: 'Islandia', de: 'Island', pl: 'Islandia', ru: 'Исландия', uk: 'Ісландія', bg: 'Исландия', ro: 'Islanda', hu: 'Izland', sk: 'Island' } },
      { code: 'ie', name: { en: 'Ireland', es: 'Irlanda', de: 'Irland', pl: 'Irlandia', ru: 'Ирландия', uk: 'Ірландія', bg: 'Ирландия', ro: 'Irlanda', hu: 'Írország', sk: 'Írsko' } },
      { code: 'it', name: { en: 'Italy', es: 'Italia', de: 'Italien', pl: 'Włochy', ru: 'Италия', uk: 'Італія', bg: 'Италия', ro: 'Italia', hu: 'Olaszország', sk: 'Taliansko' } },
      { code: 'xk', name: { en: 'Kosovo', es: 'Kosovo', de: 'Kosovo', pl: 'Kosowo', ru: 'Косово', uk: 'Косово', bg: 'Косово', ro: 'Kosovo', hu: 'Koszovó', sk: 'Kosovo' } },
      { code: 'lv', name: { en: 'Latvia', es: 'Letonia', de: 'Lettland', pl: 'Łotwa', ru: 'Латвия', uk: 'Латвія', bg: 'Латвия', ro: 'Letonia', hu: 'Lettország', sk: 'Lotyšsko' } },
      { code: 'li', name: { en: 'Liechtenstein', es: 'Liechtenstein', de: 'Liechtenstein', pl: 'Liechtenstein', ru: 'Лихтенштейн', uk: 'Ліхтенштейн', bg: 'Лихтенщайн', ro: 'Liechtenstein', hu: 'Liechtenstein', sk: 'Lichtenštajnsko' } },
      { code: 'lt', name: { en: 'Lithuania', es: 'Lituania', de: 'Litauen', pl: 'Litwa', ru: 'Литва', uk: 'Литва', bg: 'Литва', ro: 'Lituania', hu: 'Litvánia', sk: 'Litva' } },
      { code: 'lu', name: { en: 'Luxembourg', es: 'Luxemburgo', de: 'Luxemburg', pl: 'Luksemburg', ru: 'Люксембург', uk: 'Люксембург', bg: 'Люксембург', ro: 'Luxemburg', hu: 'Luxemburg', sk: 'Luxembursko' } },
      { code: 'mt', name: { en: 'Malta', es: 'Malta', de: 'Malta', pl: 'Malta', ru: 'Мальта', uk: 'Мальта', bg: 'Малта', ro: 'Malta', hu: 'Málta', sk: 'Malta' } },
      { code: 'md', name: { en: 'Moldova', es: 'Moldavia', de: 'Moldawien', pl: 'Mołdawia', ru: 'Молдова', uk: 'Молдова', bg: 'Молдова', ro: 'Moldova', hu: 'Moldova', sk: 'Moldavsko' } },
      { code: 'mc', name: { en: 'Monaco', es: 'Mónaco', de: 'Monaco', pl: 'Monako', ru: 'Монако', uk: 'Монако', bg: 'Монако', ro: 'Monaco', hu: 'Monaco', sk: 'Monako' } },
      { code: 'me', name: { en: 'Montenegro', es: 'Montenegro', de: 'Montenegro', pl: 'Czarnogóra', ru: 'Черногория', uk: 'Чорногорія', bg: 'Черна гора', ro: 'Muntenegru', hu: 'Montenegró', sk: 'Čierna Hora' } },
      { code: 'nl', name: { en: 'Netherlands', es: 'Países Bajos', de: 'Niederlande', pl: 'Holandia', ru: 'Нидерланды', uk: 'Нідерланди', bg: 'Нидерландия', ro: 'Țările de Jos', hu: 'Hollandia', sk: 'Holandsko' } },
      { code: 'mk', name: { en: 'North Macedonia', es: 'Macedonia del Norte', de: 'Nordmazedonien', pl: 'Macedonia Północna', ru: 'Северная Македония', uk: 'Північна Македонія', bg: 'Северна Македония', ro: 'Macedonia de Nord', hu: 'Észak-Macedónia', sk: 'Severné Macedónsko' } },
      { code: 'no', name: { en: 'Norway', es: 'Noruega', de: 'Norwegen', pl: 'Norwegia', ru: 'Норвегия', uk: 'Норвегія', bg: 'Норвегия', ro: 'Norvegia', hu: 'Norvégia', sk: 'Nórsko' } },
      { code: 'pl', name: { en: 'Poland', es: 'Polonia', de: 'Polen', pl: 'Polska', ru: 'Польша', uk: 'Польща', bg: 'Полша', ro: 'Polonia', hu: 'Lengyelország', sk: 'Poľsko' } },
      { code: 'pt', name: { en: 'Portugal', es: 'Portugal', de: 'Portugal', pl: 'Portugalia', ru: 'Португалия', uk: 'Португалія', bg: 'Португалия', ro: 'Portugalia', hu: 'Portugália', sk: 'Portugalsko' } },
      { code: 'ro', name: { en: 'Romania', es: 'Rumania', de: 'Rumänien', pl: 'Rumunia', ru: 'Румыния', uk: 'Румунія', bg: 'Румъния', ro: 'România', hu: 'Románia', sk: 'Rumunsko' } },
      { code: 'ru', name: { en: 'Russia', es: 'Rusia', de: 'Russland', pl: 'Rosja', ru: 'Россия', uk: 'Росія', bg: 'Русия', ro: 'Rusia', hu: 'Oroszország', sk: 'Rusko' } },
      { code: 'sm', name: { en: 'San Marino', es: 'San Marino', de: 'San Marino', pl: 'San Marino', ru: 'Сан-Марино', uk: 'Сан-Марино', bg: 'Сан Марино', ro: 'San Marino', hu: 'San Marino', sk: 'San Maríno' } },
      { code: 'rs', name: { en: 'Serbia', es: 'Serbia', de: 'Serbien', pl: 'Serbia', ru: 'Сербия', uk: 'Сербія', bg: 'Сърбия', ro: 'Serbia', hu: 'Szerbia', sk: 'Srbsko' } },
      { code: 'sk', name: { en: 'Slovakia', es: 'Eslovaquia', de: 'Slowakei', pl: 'Słowacja', ru: 'Словакия', uk: 'Словаччина', bg: 'Словакия', ro: 'Slovacia', hu: 'Szlovákia', sk: 'Slovensko' } },
      { code: 'si', name: { en: 'Slovenia', es: 'Eslovenia', de: 'Slowenien', pl: 'Słowenia', ru: 'Словения', uk: 'Словенія', bg: 'Словения', ro: 'Slovenia', hu: 'Szlovénia', sk: 'Slovinsko' } },
      { code: 'es', name: { en: 'Spain', es: 'España', de: 'Spanien', pl: 'Hiszpania', ru: 'Испания', uk: 'Іспанія', bg: 'Испания', ro: 'Spania', hu: 'Spanyolország', sk: 'Španielsko' } },
      { code: 'se', name: { en: 'Sweden', es: 'Suecia', de: 'Schweden', pl: 'Szwecja', ru: 'Швеция', uk: 'Швеція', bg: 'Швеция', ro: 'Suedia', hu: 'Svédország', sk: 'Švédsko' } },
      { code: 'ch', name: { en: 'Switzerland', es: 'Suiza', de: 'Schweiz', pl: 'Szwajcaria', ru: 'Швейцария', uk: 'Швейцарія', bg: 'Швейцария', ro: 'Elveția', hu: 'Svájc', sk: 'Švajčiarsko' } },
      { code: 'ua', name: { en: 'Ukraine', es: 'Ucrania', de: 'Ukraine', pl: 'Ukraina', ru: 'Украина', uk: 'Україна', bg: 'Украйна', ro: 'Ucraina', hu: 'Ukrajna', sk: 'Ukrajina' } },
      { code: 'gb', name: { en: 'United Kingdom', es: 'Reino Unido', de: 'Vereinigtes Königreich', pl: 'Wielka Brytania', ru: 'Великобритания', uk: 'Велика Британія', bg: 'Обединено кралство', ro: 'Regatul Unit', hu: 'Egyesült Királyság', sk: 'Spojené kráľovstvo' } },
      { code: 'va', name: { en: 'Vatican City', es: 'Ciudad del Vaticano', de: 'Vatikanstadt', pl: 'Watykan', ru: 'Ватикан', uk: 'Ватикан', bg: 'Ватикана', ro: 'Vatican', hu: 'Vatikán', sk: 'Vatikán' } },
    ],
  },
  {
    id: 'asia',
    countries: [
      { code: 'af', name: { en: 'Afghanistan', es: 'Afganistán', de: 'Afghanistan', pl: 'Afganistan', ru: 'Афганистан', uk: 'Афганістан', bg: 'Афганистан', ro: 'Afganistan', hu: 'Afganisztán', sk: 'Afganistan' } },
      { code: 'am', name: { en: 'Armenia', es: 'Armenia', de: 'Armenien', pl: 'Armenia', ru: 'Армения', uk: 'Вірменія', bg: 'Армения', ro: 'Armenia', hu: 'Örményország', sk: 'Arménsko' } },
      { code: 'az', name: { en: 'Azerbaijan', es: 'Azerbaiyán', de: 'Aserbaidschan', pl: 'Azerbejdżan', ru: 'Азербайджан', uk: 'Азербайджан', bg: 'Азербайджан', ro: 'Azerbaidjan', hu: 'Azerbajdzsán', sk: 'Azerbajdžan' } },
      { code: 'bh', name: { en: 'Bahrain', es: 'Baréin', de: 'Bahrain', pl: 'Bahrajn', ru: 'Бахрейн', uk: 'Бахрейн', bg: 'Бахрейн', ro: 'Bahrain', hu: 'Bahrein', sk: 'Bahrajn' } },
      { code: 'bd', name: { en: 'Bangladesh', es: 'Bangladés', de: 'Bangladesch', pl: 'Bangladesz', ru: 'Бангладеш', uk: 'Бангладеш', bg: 'Бангладеш', ro: 'Bangladesh', hu: 'Banglades', sk: 'Bangladéš' } },
      { code: 'bt', name: { en: 'Bhutan', es: 'Bután', de: 'Bhutan', pl: 'Bhutan', ru: 'Бутан', uk: 'Бутан', bg: 'Бутан', ro: 'Bhutan', hu: 'Bhután', sk: 'Bhután' } },
      { code: 'bn', name: { en: 'Brunei', es: 'Brunéi', de: 'Brunei', pl: 'Brunei', ru: 'Бруней', uk: 'Бруней', bg: 'Бруней', ro: 'Brunei', hu: 'Brunei', sk: 'Brunej' } },
      { code: 'kh', name: { en: 'Cambodia', es: 'Camboya', de: 'Kambodscha', pl: 'Kambodża', ru: 'Камбоджа', uk: 'Камбоджа', bg: 'Камбоджа', ro: 'Cambodgia', hu: 'Kambodzsa', sk: 'Kambodža' } },
      { code: 'cn', name: { en: 'China', es: 'China', de: 'China', pl: 'Chiny', ru: 'Китай', uk: 'Китай', bg: 'Китай', ro: 'China', hu: 'Kína', sk: 'Čína' } },
      { code: 'ge', name: { en: 'Georgia', es: 'Georgia', de: 'Georgien', pl: 'Gruzja', ru: 'Грузия', uk: 'Грузія', bg: 'Грузия', ro: 'Georgia', hu: 'Grúzia', sk: 'Gruzínsko' } },
      { code: 'in', name: { en: 'India', es: 'India', de: 'Indien', pl: 'Indie', ru: 'Индия', uk: 'Індія', bg: 'Индия', ro: 'India', hu: 'India', sk: 'India' } },
      { code: 'id', name: { en: 'Indonesia', es: 'Indonesia', de: 'Indonesien', pl: 'Indonezja', ru: 'Индонезия', uk: 'Індонезія', bg: 'Индонезия', ro: 'Indonezia', hu: 'Indonézia', sk: 'Indonézia' } },
      { code: 'ir', name: { en: 'Iran', es: 'Irán', de: 'Iran', pl: 'Iran', ru: 'Иран', uk: 'Іран', bg: 'Иран', ro: 'Iran', hu: 'Irán', sk: 'Irán' } },
      { code: 'iq', name: { en: 'Iraq', es: 'Irak', de: 'Irak', pl: 'Irak', ru: 'Ирак', uk: 'Ірак', bg: 'Ирак', ro: 'Irak', hu: 'Irak', sk: 'Irak' } },
      { code: 'il', name: { en: 'Israel', es: 'Israel', de: 'Israel', pl: 'Izrael', ru: 'Израиль', uk: 'Ізраїль', bg: 'Израел', ro: 'Israel', hu: 'Izrael', sk: 'Izrael' } },
      { code: 'jp', name: { en: 'Japan', es: 'Japón', de: 'Japan', pl: 'Japonia', ru: 'Япония', uk: 'Японія', bg: 'Япония', ro: 'Japonia', hu: 'Japán', sk: 'Japonsko' } },
      { code: 'jo', name: { en: 'Jordan', es: 'Jordania', de: 'Jordanien', pl: 'Jordania', ru: 'Иордания', uk: 'Йорданія', bg: 'Йордания', ro: 'Iordania', hu: 'Jordánia', sk: 'Jordánsko' } },
      { code: 'kz', name: { en: 'Kazakhstan', es: 'Kazajistán', de: 'Kasachstan', pl: 'Kazachstan', ru: 'Казахстан', uk: 'Казахстан', bg: 'Казахстан', ro: 'Kazahstan', hu: 'Kazahsztán', sk: 'Kazachstan' } },
      { code: 'kw', name: { en: 'Kuwait', es: 'Kuwait', de: 'Kuwait', pl: 'Kuwejt', ru: 'Кувейт', uk: 'Кувейт', bg: 'Кувейт', ro: 'Kuweit', hu: 'Kuvait', sk: 'Kuvajt' } },
      { code: 'kg', name: { en: 'Kyrgyzstan', es: 'Kirguistán', de: 'Kirgisistan', pl: 'Kirgistan', ru: 'Киргизия', uk: 'Киргизстан', bg: 'Киргизстан', ro: 'Kârgâzstan', hu: 'Kirgizisztán', sk: 'Kirgizsko' } },
      { code: 'la', name: { en: 'Laos', es: 'Laos', de: 'Laos', pl: 'Laos', ru: 'Лаос', uk: 'Лаос', bg: 'Лаос', ro: 'Laos', hu: 'Laosz', sk: 'Laos' } },
      { code: 'lb', name: { en: 'Lebanon', es: 'Líbano', de: 'Libanon', pl: 'Liban', ru: 'Ливан', uk: 'Ліван', bg: 'Ливан', ro: 'Liban', hu: 'Libanon', sk: 'Libanon' } },
      { code: 'my', name: { en: 'Malaysia', es: 'Malasia', de: 'Malaysia', pl: 'Malezja', ru: 'Малайзия', uk: 'Малайзія', bg: 'Малайзия', ro: 'Malaezia', hu: 'Malajzia', sk: 'Malajzia' } },
      { code: 'mv', name: { en: 'Maldives', es: 'Maldivas', de: 'Malediven', pl: 'Malediwy', ru: 'Мальдивы', uk: 'Мальдіви', bg: 'Малдиви', ro: 'Maldive', hu: 'Maldív-szigetek', sk: 'Maldivy' } },
      { code: 'mn', name: { en: 'Mongolia', es: 'Mongolia', de: 'Mongolei', pl: 'Mongolia', ru: 'Монголия', uk: 'Монголія', bg: 'Монголия', ro: 'Mongolia', hu: 'Mongólia', sk: 'Mongolsko' } },
      { code: 'mm', name: { en: 'Myanmar', es: 'Myanmar', de: 'Myanmar', pl: 'Mjanma', ru: 'Мьянма', uk: "М'янма", bg: 'Мианмар', ro: 'Myanmar', hu: 'Mianmar', sk: 'Mjanmarsko' } },
      { code: 'np', name: { en: 'Nepal', es: 'Nepal', de: 'Nepal', pl: 'Nepal', ru: 'Непал', uk: 'Непал', bg: 'Непал', ro: 'Nepal', hu: 'Nepál', sk: 'Nepál' } },
      { code: 'kp', name: { en: 'North Korea', es: 'Corea del Norte', de: 'Nordkorea', pl: 'Korea Północna', ru: 'Северная Корея', uk: 'Північна Корея', bg: 'Северна Корея', ro: 'Coreea de Nord', hu: 'Észak-Korea', sk: 'Severná Kórea' } },
      { code: 'om', name: { en: 'Oman', es: 'Omán', de: 'Oman', pl: 'Oman', ru: 'Оман', uk: 'Оман', bg: 'Оман', ro: 'Oman', hu: 'Omán', sk: 'Omán' } },
      { code: 'pk', name: { en: 'Pakistan', es: 'Pakistán', de: 'Pakistan', pl: 'Pakistan', ru: 'Пакистан', uk: 'Пакистан', bg: 'Пакистан', ro: 'Pakistan', hu: 'Pakisztán', sk: 'Pakistan' } },
      { code: 'ps', name: { en: 'Palestine', es: 'Palestina', de: 'Palästina', pl: 'Palestyna', ru: 'Палестина', uk: 'Палестина', bg: 'Палестина', ro: 'Palestina', hu: 'Palesztina', sk: 'Palestína' } },
      { code: 'ph', name: { en: 'Philippines', es: 'Filipinas', de: 'Philippinen', pl: 'Filipiny', ru: 'Филиппины', uk: 'Філіппіни', bg: 'Филипини', ro: 'Filipine', hu: 'Fülöp-szigetek', sk: 'Filipíny' } },
      { code: 'qa', name: { en: 'Qatar', es: 'Catar', de: 'Katar', pl: 'Katar', ru: 'Катар', uk: 'Катар', bg: 'Катар', ro: 'Qatar', hu: 'Katar', sk: 'Katar' } },
      { code: 'sa', name: { en: 'Saudi Arabia', es: 'Arabia Saudita', de: 'Saudi-Arabien', pl: 'Arabia Saudyjska', ru: 'Саудовская Аравия', uk: 'Саудівська Аравія', bg: 'Саудитска Арабия', ro: 'Arabia Saudită', hu: 'Szaúd-Arábia', sk: 'Saudská Arábia' } },
      { code: 'sg', name: { en: 'Singapore', es: 'Singapur', de: 'Singapur', pl: 'Singapur', ru: 'Сингапур', uk: 'Сінгапур', bg: 'Сингапур', ro: 'Singapore', hu: 'Szingapúr', sk: 'Singapur' } },
      { code: 'kr', name: { en: 'South Korea', es: 'Corea del Sur', de: 'Südkorea', pl: 'Korea Południowa', ru: 'Южная Корея', uk: 'Південна Корея', bg: 'Южна Корея', ro: 'Coreea de Sud', hu: 'Dél-Korea', sk: 'Južná Kórea' } },
      { code: 'lk', name: { en: 'Sri Lanka', es: 'Sri Lanka', de: 'Sri Lanka', pl: 'Sri Lanka', ru: 'Шри-Ланка', uk: 'Шрі-Ланка', bg: 'Шри Ланка', ro: 'Sri Lanka', hu: 'Srí Lanka', sk: 'Srí Lanka' } },
      { code: 'sy', name: { en: 'Syria', es: 'Siria', de: 'Syrien', pl: 'Syria', ru: 'Сирия', uk: 'Сирія', bg: 'Сирия', ro: 'Siria', hu: 'Szíria', sk: 'Sýria' } },
      { code: 'tw', name: { en: 'Taiwan', es: 'Taiwán', de: 'Taiwan', pl: 'Tajwan', ru: 'Тайвань', uk: 'Тайвань', bg: 'Тайван', ro: 'Taiwan', hu: 'Tajvan', sk: 'Taiwan' } },
      { code: 'tj', name: { en: 'Tajikistan', es: 'Tayikistán', de: 'Tadschikistan', pl: 'Tadżykistan', ru: 'Таджикистан', uk: 'Таджикистан', bg: 'Таджикистан', ro: 'Tadjikistan', hu: 'Tádzsikisztán', sk: 'Tadžikistan' } },
      { code: 'th', name: { en: 'Thailand', es: 'Tailandia', de: 'Thailand', pl: 'Tajlandia', ru: 'Таиланд', uk: 'Таїланд', bg: 'Тайланд', ro: 'Thailanda', hu: 'Thaiföld', sk: 'Thajsko' } },
      { code: 'tl', name: { en: 'Timor-Leste', es: 'Timor Oriental', de: 'Osttimor', pl: 'Timor Wschodni', ru: 'Восточный Тимор', uk: 'Східний Тимор', bg: 'Източен Тимор', ro: 'Timorul de Est', hu: 'Kelet-Timor', sk: 'Východný Timor' } },
      { code: 'tr', name: { en: 'Turkey', es: 'Turquía', de: 'Türkei', pl: 'Turcja', ru: 'Турция', uk: 'Туреччина', bg: 'Турция', ro: 'Turcia', hu: 'Törökország', sk: 'Turecko' } },
      { code: 'tm', name: { en: 'Turkmenistan', es: 'Turkmenistán', de: 'Turkmenistan', pl: 'Turkmenistan', ru: 'Туркменистан', uk: 'Туркменістан', bg: 'Туркменистан', ro: 'Turkmenistan', hu: 'Türkmenisztán', sk: 'Turkménsko' } },
      { code: 'ae', name: { en: 'United Arab Emirates', es: 'Emiratos Árabes Unidos', de: 'Vereinigte Arabische Emirate', pl: 'Zjednoczone Emiraty Arabskie', ru: 'ОАЭ', uk: 'ОАЕ', bg: 'ОАЕ', ro: 'Emiratele Arabe Unite', hu: 'Egyesült Arab Emírségek', sk: 'Spojené arabské emiráty' } },
      { code: 'uz', name: { en: 'Uzbekistan', es: 'Uzbekistán', de: 'Usbekistan', pl: 'Uzbekistan', ru: 'Узбекистан', uk: 'Узбекистан', bg: 'Узбекистан', ro: 'Uzbekistan', hu: 'Üzbegisztán', sk: 'Uzbekistan' } },
      { code: 'vn', name: { en: 'Vietnam', es: 'Vietnam', de: 'Vietnam', pl: 'Wietnam', ru: 'Вьетнам', uk: "В'єтнам", bg: 'Виетнам', ro: 'Vietnam', hu: 'Vietnám', sk: 'Vietnam' } },
      { code: 'ye', name: { en: 'Yemen', es: 'Yemen', de: 'Jemen', pl: 'Jemen', ru: 'Йемен', uk: 'Ємен', bg: 'Йемен', ro: 'Yemen', hu: 'Jemen', sk: 'Jemen' } },
    ],
  },
  {
    id: 'africa',
    countries: [
      { code: 'dz', name: { en: 'Algeria', es: 'Argelia', de: 'Algerien', pl: 'Algieria', ru: 'Алжир', uk: 'Алжир', bg: 'Алжир', ro: 'Algeria', hu: 'Algéria', sk: 'Alžírsko' } },
      { code: 'ao', name: { en: 'Angola', es: 'Angola', de: 'Angola', pl: 'Angola', ru: 'Ангола', uk: 'Ангола', bg: 'Ангола', ro: 'Angola', hu: 'Angola', sk: 'Angola' } },
      { code: 'bj', name: { en: 'Benin', es: 'Benín', de: 'Benin', pl: 'Benin', ru: 'Бенин', uk: 'Бенін', bg: 'Бенин', ro: 'Benin', hu: 'Benin', sk: 'Benin' } },
      { code: 'bw', name: { en: 'Botswana', es: 'Botsuana', de: 'Botswana', pl: 'Botswana', ru: 'Ботсвана', uk: 'Ботсвана', bg: 'Ботсвана', ro: 'Botswana', hu: 'Botswana', sk: 'Botswana' } },
      { code: 'bf', name: { en: 'Burkina Faso', es: 'Burkina Faso', de: 'Burkina Faso', pl: 'Burkina Faso', ru: 'Буркина-Фасо', uk: 'Буркіна-Фасо', bg: 'Буркина Фасо', ro: 'Burkina Faso', hu: 'Burkina Faso', sk: 'Burkina Faso' } },
      { code: 'bi', name: { en: 'Burundi', es: 'Burundi', de: 'Burundi', pl: 'Burundi', ru: 'Бурунди', uk: 'Бурунді', bg: 'Бурунди', ro: 'Burundi', hu: 'Burundi', sk: 'Burundi' } },
      { code: 'cv', name: { en: 'Cabo Verde', es: 'Cabo Verde', de: 'Kap Verde', pl: 'Republika Zielonego Przylądka', ru: 'Кабо-Верде', uk: 'Кабо-Верде', bg: 'Кабо Верде', ro: 'Capul Verde', hu: 'Zöld-foki Köztársaság', sk: 'Kapverdy' } },
      { code: 'cm', name: { en: 'Cameroon', es: 'Camerún', de: 'Kamerun', pl: 'Kamerun', ru: 'Камерун', uk: 'Камерун', bg: 'Камерун', ro: 'Camerun', hu: 'Kamerun', sk: 'Kamerun' } },
      { code: 'cf', name: { en: 'Central African Republic', es: 'República Centroafricana', de: 'Zentralafrikanische Republik', pl: 'Republika Środkowoafrykańska', ru: 'ЦАР', uk: 'ЦАР', bg: 'ЦАР', ro: 'Republica Centrafricană', hu: 'Közép-afrikai Köztársaság', sk: 'Stredoafrická republika' } },
      { code: 'td', name: { en: 'Chad', es: 'Chad', de: 'Tschad', pl: 'Czad', ru: 'Чад', uk: 'Чад', bg: 'Чад', ro: 'Ciad', hu: 'Csád', sk: 'Čad' } },
      { code: 'km', name: { en: 'Comoros', es: 'Comoras', de: 'Komoren', pl: 'Komory', ru: 'Коморы', uk: 'Комори', bg: 'Коморски острови', ro: 'Comore', hu: 'Comore-szigetek', sk: 'Komory' } },
      { code: 'cg', name: { en: 'Congo', es: 'Congo', de: 'Kongo', pl: 'Kongo', ru: 'Конго', uk: 'Конго', bg: 'Конго', ro: 'Congo', hu: 'Kongó', sk: 'Kongo' } },
      { code: 'cd', name: { en: 'DR Congo', es: 'RD del Congo', de: 'DR Kongo', pl: 'DR Konga', ru: 'ДР Конго', uk: 'ДР Конго', bg: 'ДР Конго', ro: 'RD Congo', hu: 'Kongói DK', sk: 'DR Kongo' } },
      { code: 'ci', name: { en: "Côte d'Ivoire", es: 'Costa de Marfil', de: 'Elfenbeinküste', pl: 'Wybrzeże Kości Słoniowej', ru: "Кот-д'Ивуар", uk: "Кот-д'Івуар", bg: "Кот д'Ивоар", ro: 'Coasta de Fildeș', hu: 'Elefántcsontpart', sk: 'Pobrežie Slonoviny' } },
      { code: 'dj', name: { en: 'Djibouti', es: 'Yibuti', de: 'Dschibuti', pl: 'Dżibuti', ru: 'Джибути', uk: 'Джибуті', bg: 'Джибути', ro: 'Djibouti', hu: 'Dzsibuti', sk: 'Džibutsko' } },
      { code: 'eg', name: { en: 'Egypt', es: 'Egipto', de: 'Ägypten', pl: 'Egipt', ru: 'Египет', uk: 'Єгипет', bg: 'Египет', ro: 'Egipt', hu: 'Egyiptom', sk: 'Egypt' } },
      { code: 'gq', name: { en: 'Equatorial Guinea', es: 'Guinea Ecuatorial', de: 'Äquatorialguinea', pl: 'Gwinea Równikowa', ru: 'Экваториальная Гвинея', uk: 'Екваторіальна Гвінея', bg: 'Екваториална Гвинея', ro: 'Guineea Ecuatorială', hu: 'Egyenlítői-Guinea', sk: 'Rovníková Guinea' } },
      { code: 'er', name: { en: 'Eritrea', es: 'Eritrea', de: 'Eritrea', pl: 'Erytrea', ru: 'Эритрея', uk: 'Еритрея', bg: 'Еритрея', ro: 'Eritreea', hu: 'Eritrea', sk: 'Eritrea' } },
      { code: 'sz', name: { en: 'Eswatini', es: 'Esuatini', de: 'Eswatini', pl: 'Eswatini', ru: 'Эсватини', uk: 'Есватіні', bg: 'Есватини', ro: 'Eswatini', hu: 'Eswatini', sk: 'Eswatini' } },
      { code: 'et', name: { en: 'Ethiopia', es: 'Etiopía', de: 'Äthiopien', pl: 'Etiopia', ru: 'Эфиопия', uk: 'Ефіопія', bg: 'Етиопия', ro: 'Etiopia', hu: 'Etiópia', sk: 'Etiópia' } },
      { code: 'ga', name: { en: 'Gabon', es: 'Gabón', de: 'Gabun', pl: 'Gabon', ru: 'Габон', uk: 'Габон', bg: 'Габон', ro: 'Gabon', hu: 'Gabon', sk: 'Gabon' } },
      { code: 'gm', name: { en: 'Gambia', es: 'Gambia', de: 'Gambia', pl: 'Gambia', ru: 'Гамбия', uk: 'Гамбія', bg: 'Гамбия', ro: 'Gambia', hu: 'Gambia', sk: 'Gambia' } },
      { code: 'gh', name: { en: 'Ghana', es: 'Ghana', de: 'Ghana', pl: 'Ghana', ru: 'Гана', uk: 'Гана', bg: 'Гана', ro: 'Ghana', hu: 'Ghána', sk: 'Ghana' } },
      { code: 'gn', name: { en: 'Guinea', es: 'Guinea', de: 'Guinea', pl: 'Gwinea', ru: 'Гвинея', uk: 'Гвінея', bg: 'Гвинея', ro: 'Guineea', hu: 'Guinea', sk: 'Guinea' } },
      { code: 'gw', name: { en: 'Guinea-Bissau', es: 'Guinea-Bisáu', de: 'Guinea-Bissau', pl: 'Gwinea Bissau', ru: 'Гвинея-Бисау', uk: 'Гвінея-Бісау', bg: 'Гвинея-Бисау', ro: 'Guineea-Bissau', hu: 'Bissau-Guinea', sk: 'Guinea-Bissau' } },
      { code: 'ke', name: { en: 'Kenya', es: 'Kenia', de: 'Kenia', pl: 'Kenia', ru: 'Кения', uk: 'Кенія', bg: 'Кения', ro: 'Kenya', hu: 'Kenya', sk: 'Keňa' } },
      { code: 'ls', name: { en: 'Lesotho', es: 'Lesoto', de: 'Lesotho', pl: 'Lesotho', ru: 'Лесото', uk: 'Лесото', bg: 'Лесото', ro: 'Lesotho', hu: 'Lesotho', sk: 'Lesotho' } },
      { code: 'lr', name: { en: 'Liberia', es: 'Liberia', de: 'Liberia', pl: 'Liberia', ru: 'Либерия', uk: 'Ліберія', bg: 'Либерия', ro: 'Liberia', hu: 'Libéria', sk: 'Libéria' } },
      { code: 'ly', name: { en: 'Libya', es: 'Libia', de: 'Libyen', pl: 'Libia', ru: 'Ливия', uk: 'Лівія', bg: 'Либия', ro: 'Libia', hu: 'Líbia', sk: 'Líbya' } },
      { code: 'mg', name: { en: 'Madagascar', es: 'Madagascar', de: 'Madagaskar', pl: 'Madagaskar', ru: 'Мадагаскар', uk: 'Мадагаскар', bg: 'Мадагаскар', ro: 'Madagascar', hu: 'Madagaszkár', sk: 'Madagaskar' } },
      { code: 'mw', name: { en: 'Malawi', es: 'Malaui', de: 'Malawi', pl: 'Malawi', ru: 'Малави', uk: 'Малаві', bg: 'Малави', ro: 'Malawi', hu: 'Malawi', sk: 'Malawi' } },
      { code: 'ml', name: { en: 'Mali', es: 'Malí', de: 'Mali', pl: 'Mali', ru: 'Мали', uk: 'Малі', bg: 'Мали', ro: 'Mali', hu: 'Mali', sk: 'Mali' } },
      { code: 'mr', name: { en: 'Mauritania', es: 'Mauritania', de: 'Mauretanien', pl: 'Mauretania', ru: 'Мавритания', uk: 'Мавританія', bg: 'Мавритания', ro: 'Mauritania', hu: 'Mauritánia', sk: 'Mauritánia' } },
      { code: 'mu', name: { en: 'Mauritius', es: 'Mauricio', de: 'Mauritius', pl: 'Mauritius', ru: 'Маврикий', uk: 'Маврикій', bg: 'Мавриций', ro: 'Mauritius', hu: 'Mauritius', sk: 'Maurícius' } },
      { code: 'ma', name: { en: 'Morocco', es: 'Marruecos', de: 'Marokko', pl: 'Maroko', ru: 'Марокко', uk: 'Марокко', bg: 'Мароко', ro: 'Maroc', hu: 'Marokkó', sk: 'Maroko' } },
      { code: 'mz', name: { en: 'Mozambique', es: 'Mozambique', de: 'Mosambik', pl: 'Mozambik', ru: 'Мозамбик', uk: 'Мозамбік', bg: 'Мозамбик', ro: 'Mozambic', hu: 'Mozambik', sk: 'Mozambik' } },
      { code: 'na', name: { en: 'Namibia', es: 'Namibia', de: 'Namibia', pl: 'Namibia', ru: 'Намибия', uk: 'Намібія', bg: 'Намибия', ro: 'Namibia', hu: 'Namíbia', sk: 'Namíbia' } },
      { code: 'ne', name: { en: 'Niger', es: 'Níger', de: 'Niger', pl: 'Niger', ru: 'Нигер', uk: 'Нігер', bg: 'Нигер', ro: 'Niger', hu: 'Niger', sk: 'Niger' } },
      { code: 'ng', name: { en: 'Nigeria', es: 'Nigeria', de: 'Nigeria', pl: 'Nigeria', ru: 'Нигерия', uk: 'Нігерія', bg: 'Нигерия', ro: 'Nigeria', hu: 'Nigéria', sk: 'Nigéria' } },
      { code: 'rw', name: { en: 'Rwanda', es: 'Ruanda', de: 'Ruanda', pl: 'Rwanda', ru: 'Руанда', uk: 'Руанда', bg: 'Руанда', ro: 'Rwanda', hu: 'Ruanda', sk: 'Rwanda' } },
      { code: 'st', name: { en: 'São Tomé and Príncipe', es: 'Santo Tomé y Príncipe', de: 'São Tomé und Príncipe', pl: 'Wyspy Świętego Tomasza i Książęca', ru: 'Сан-Томе и Принсипи', uk: 'Сан-Томе і Принсіпі', bg: 'Сао Томе и Принсипи', ro: 'São Tomé și Príncipe', hu: 'São Tomé és Príncipe', sk: 'Svätý Tomáš a Princov ostrov' } },
      { code: 'sn', name: { en: 'Senegal', es: 'Senegal', de: 'Senegal', pl: 'Senegal', ru: 'Сенегал', uk: 'Сенегал', bg: 'Сенегал', ro: 'Senegal', hu: 'Szenegál', sk: 'Senegal' } },
      { code: 'sc', name: { en: 'Seychelles', es: 'Seychelles', de: 'Seychellen', pl: 'Seszele', ru: 'Сейшелы', uk: 'Сейшели', bg: 'Сейшели', ro: 'Seychelles', hu: 'Seychelle-szigetek', sk: 'Seychely' } },
      { code: 'sl', name: { en: 'Sierra Leone', es: 'Sierra Leona', de: 'Sierra Leone', pl: 'Sierra Leone', ru: 'Сьерра-Леоне', uk: 'Сьєрра-Леоне', bg: 'Сиера Леоне', ro: 'Sierra Leone', hu: 'Sierra Leone', sk: 'Sierra Leone' } },
      { code: 'so', name: { en: 'Somalia', es: 'Somalia', de: 'Somalia', pl: 'Somalia', ru: 'Сомали', uk: 'Сомалі', bg: 'Сомалия', ro: 'Somalia', hu: 'Szomália', sk: 'Somálsko' } },
      { code: 'za', name: { en: 'South Africa', es: 'Sudáfrica', de: 'Südafrika', pl: 'Republika Południowej Afryki', ru: 'ЮАР', uk: 'ПАР', bg: 'ЮАР', ro: 'Africa de Sud', hu: 'Dél-Afrika', sk: 'Juhoafrická republika' } },
      { code: 'ss', name: { en: 'South Sudan', es: 'Sudán del Sur', de: 'Südsudan', pl: 'Sudan Południowy', ru: 'Южный Судан', uk: 'Південний Судан', bg: 'Южен Судан', ro: 'Sudanul de Sud', hu: 'Dél-Szudán', sk: 'Južný Sudán' } },
      { code: 'sd', name: { en: 'Sudan', es: 'Sudán', de: 'Sudan', pl: 'Sudan', ru: 'Судан', uk: 'Судан', bg: 'Судан', ro: 'Sudan', hu: 'Szudán', sk: 'Sudán' } },
      { code: 'tz', name: { en: 'Tanzania', es: 'Tanzania', de: 'Tansania', pl: 'Tanzania', ru: 'Танзания', uk: 'Танзанія', bg: 'Танзания', ro: 'Tanzania', hu: 'Tanzánia', sk: 'Tanzánia' } },
      { code: 'tg', name: { en: 'Togo', es: 'Togo', de: 'Togo', pl: 'Togo', ru: 'Того', uk: 'Того', bg: 'Того', ro: 'Togo', hu: 'Togo', sk: 'Togo' } },
      { code: 'tn', name: { en: 'Tunisia', es: 'Túnez', de: 'Tunesien', pl: 'Tunezja', ru: 'Тунис', uk: 'Туніс', bg: 'Тунис', ro: 'Tunisia', hu: 'Tunézia', sk: 'Tunisko' } },
      { code: 'ug', name: { en: 'Uganda', es: 'Uganda', de: 'Uganda', pl: 'Uganda', ru: 'Уганда', uk: 'Уганда', bg: 'Уганда', ro: 'Uganda', hu: 'Uganda', sk: 'Uganda' } },
      { code: 'zm', name: { en: 'Zambia', es: 'Zambia', de: 'Sambia', pl: 'Zambia', ru: 'Замбия', uk: 'Замбія', bg: 'Замбия', ro: 'Zambia', hu: 'Zambia', sk: 'Zambia' } },
      { code: 'zw', name: { en: 'Zimbabwe', es: 'Zimbabue', de: 'Simbabwe', pl: 'Zimbabwe', ru: 'Зимбабве', uk: 'Зімбабве', bg: 'Зимбабве', ro: 'Zimbabwe', hu: 'Zimbabwe', sk: 'Zimbabwe' } },
    ],
  },
  {
    id: 'north_america',
    countries: [
      { code: 'ag', name: { en: 'Antigua and Barbuda', es: 'Antigua y Barbuda', de: 'Antigua und Barbuda', pl: 'Antigua i Barbuda', ru: 'Антигуа и Барбуда', uk: 'Антигуа і Барбуда', bg: 'Антигуа и Барбуда', ro: 'Antigua și Barbuda', hu: 'Antigua és Barbuda', sk: 'Antigua a Barbuda' } },
      { code: 'bs', name: { en: 'Bahamas', es: 'Bahamas', de: 'Bahamas', pl: 'Bahamy', ru: 'Багамы', uk: 'Багами', bg: 'Бахамски острови', ro: 'Bahamas', hu: 'Bahama-szigetek', sk: 'Bahamy' } },
      { code: 'bb', name: { en: 'Barbados', es: 'Barbados', de: 'Barbados', pl: 'Barbados', ru: 'Барбадос', uk: 'Барбадос', bg: 'Барбадос', ro: 'Barbados', hu: 'Barbados', sk: 'Barbados' } },
      { code: 'bz', name: { en: 'Belize', es: 'Belice', de: 'Belize', pl: 'Belize', ru: 'Белиз', uk: 'Беліз', bg: 'Белиз', ro: 'Belize', hu: 'Belize', sk: 'Belize' } },
      { code: 'ca', name: { en: 'Canada', es: 'Canadá', de: 'Kanada', pl: 'Kanada', ru: 'Канада', uk: 'Канада', bg: 'Канада', ro: 'Canada', hu: 'Kanada', sk: 'Kanada' } },
      { code: 'cr', name: { en: 'Costa Rica', es: 'Costa Rica', de: 'Costa Rica', pl: 'Kostaryka', ru: 'Коста-Рика', uk: 'Коста-Рика', bg: 'Коста Рика', ro: 'Costa Rica', hu: 'Costa Rica', sk: 'Kostarika' } },
      { code: 'cu', name: { en: 'Cuba', es: 'Cuba', de: 'Kuba', pl: 'Kuba', ru: 'Куба', uk: 'Куба', bg: 'Куба', ro: 'Cuba', hu: 'Kuba', sk: 'Kuba' } },
      { code: 'dm', name: { en: 'Dominica', es: 'Dominica', de: 'Dominica', pl: 'Dominika', ru: 'Доминика', uk: 'Домініка', bg: 'Доминика', ro: 'Dominica', hu: 'Dominika', sk: 'Dominika' } },
      { code: 'do', name: { en: 'Dominican Republic', es: 'República Dominicana', de: 'Dominikanische Republik', pl: 'Dominikana', ru: 'Доминиканская Республика', uk: 'Домініканська Республіка', bg: 'Доминиканска република', ro: 'Republica Dominicană', hu: 'Dominikai Köztársaság', sk: 'Dominikánska republika' } },
      { code: 'sv', name: { en: 'El Salvador', es: 'El Salvador', de: 'El Salvador', pl: 'Salwador', ru: 'Сальвадор', uk: 'Сальвадор', bg: 'Салвадор', ro: 'El Salvador', hu: 'Salvador', sk: 'Salvádor' } },
      { code: 'gd', name: { en: 'Grenada', es: 'Granada', de: 'Grenada', pl: 'Grenada', ru: 'Гренада', uk: 'Гренада', bg: 'Гренада', ro: 'Grenada', hu: 'Grenada', sk: 'Grenada' } },
      { code: 'gt', name: { en: 'Guatemala', es: 'Guatemala', de: 'Guatemala', pl: 'Gwatemala', ru: 'Гватемала', uk: 'Гватемала', bg: 'Гватемала', ro: 'Guatemala', hu: 'Guatemala', sk: 'Guatemala' } },
      { code: 'ht', name: { en: 'Haiti', es: 'Haití', de: 'Haiti', pl: 'Haiti', ru: 'Гаити', uk: 'Гаїті', bg: 'Хаити', ro: 'Haiti', hu: 'Haiti', sk: 'Haiti' } },
      { code: 'hn', name: { en: 'Honduras', es: 'Honduras', de: 'Honduras', pl: 'Honduras', ru: 'Гондурас', uk: 'Гондурас', bg: 'Хондурас', ro: 'Honduras', hu: 'Honduras', sk: 'Honduras' } },
      { code: 'jm', name: { en: 'Jamaica', es: 'Jamaica', de: 'Jamaika', pl: 'Jamajka', ru: 'Ямайка', uk: 'Ямайка', bg: 'Ямайка', ro: 'Jamaica', hu: 'Jamaica', sk: 'Jamajka' } },
      { code: 'mx', name: { en: 'Mexico', es: 'México', de: 'Mexiko', pl: 'Meksyk', ru: 'Мексика', uk: 'Мексика', bg: 'Мексико', ro: 'Mexic', hu: 'Mexikó', sk: 'Mexiko' } },
      { code: 'ni', name: { en: 'Nicaragua', es: 'Nicaragua', de: 'Nicaragua', pl: 'Nikaragua', ru: 'Никарагуа', uk: 'Нікарагуа', bg: 'Никарагуа', ro: 'Nicaragua', hu: 'Nicaragua', sk: 'Nikaragua' } },
      { code: 'pa', name: { en: 'Panama', es: 'Panamá', de: 'Panama', pl: 'Panama', ru: 'Панама', uk: 'Панама', bg: 'Панама', ro: 'Panama', hu: 'Panama', sk: 'Panama' } },
      { code: 'kn', name: { en: 'Saint Kitts and Nevis', es: 'San Cristóbal y Nieves', de: 'St. Kitts und Nevis', pl: 'Saint Kitts i Nevis', ru: 'Сент-Китс и Невис', uk: 'Сент-Кітс і Невіс', bg: 'Сейнт Китс и Невис', ro: 'Sfântul Kitts și Nevis', hu: 'Saint Kitts és Nevis', sk: 'Svätý Krištof a Nevis' } },
      { code: 'lc', name: { en: 'Saint Lucia', es: 'Santa Lucía', de: 'St. Lucia', pl: 'Saint Lucia', ru: 'Сент-Люсия', uk: 'Сент-Люсія', bg: 'Сейнт Лусия', ro: 'Sfânta Lucia', hu: 'Saint Lucia', sk: 'Svätá Lucia' } },
      { code: 'vc', name: { en: 'Saint Vincent and the Grenadines', es: 'San Vicente y las Granadinas', de: 'St. Vincent und die Grenadinen', pl: 'Saint Vincent i Grenadyny', ru: 'Сент-Винсент и Гренадины', uk: 'Сент-Вінсент і Гренадини', bg: 'Сейнт Винсент и Гренадини', ro: 'Sfântul Vincent și Grenadine', hu: 'Saint Vincent és a Grenadine-szigetek', sk: 'Svätý Vincent a Grenadíny' } },
      { code: 'tt', name: { en: 'Trinidad and Tobago', es: 'Trinidad y Tobago', de: 'Trinidad und Tobago', pl: 'Trynidad i Tobago', ru: 'Тринидад и Тобаго', uk: 'Тринідад і Тобаго', bg: 'Тринидад и Тобаго', ro: 'Trinidad și Tobago', hu: 'Trinidad és Tobago', sk: 'Trinidad a Tobago' } },
      { code: 'us', name: { en: 'United States', es: 'Estados Unidos', de: 'Vereinigte Staaten', pl: 'Stany Zjednoczone', ru: 'США', uk: 'США', bg: 'САЩ', ro: 'Statele Unite', hu: 'Egyesült Államok', sk: 'Spojené štáty' } },
    ],
  },
  {
    id: 'south_america',
    countries: [
      { code: 'ar', name: { en: 'Argentina', es: 'Argentina', de: 'Argentinien', pl: 'Argentyna', ru: 'Аргентина', uk: 'Аргентина', bg: 'Аржентина', ro: 'Argentina', hu: 'Argentína', sk: 'Argentína' } },
      { code: 'bo', name: { en: 'Bolivia', es: 'Bolivia', de: 'Bolivien', pl: 'Boliwia', ru: 'Боливия', uk: 'Болівія', bg: 'Боливия', ro: 'Bolivia', hu: 'Bolívia', sk: 'Bolívia' } },
      { code: 'br', name: { en: 'Brazil', es: 'Brasil', de: 'Brasilien', pl: 'Brazylia', ru: 'Бразилия', uk: 'Бразилія', bg: 'Бразилия', ro: 'Brazilia', hu: 'Brazília', sk: 'Brazília' } },
      { code: 'cl', name: { en: 'Chile', es: 'Chile', de: 'Chile', pl: 'Chile', ru: 'Чили', uk: 'Чилі', bg: 'Чили', ro: 'Chile', hu: 'Chile', sk: 'Čile' } },
      { code: 'co', name: { en: 'Colombia', es: 'Colombia', de: 'Kolumbien', pl: 'Kolumbia', ru: 'Колумбия', uk: 'Колумбія', bg: 'Колумбия', ro: 'Columbia', hu: 'Kolumbia', sk: 'Kolumbia' } },
      { code: 'ec', name: { en: 'Ecuador', es: 'Ecuador', de: 'Ecuador', pl: 'Ekwador', ru: 'Эквадор', uk: 'Еквадор', bg: 'Еквадор', ro: 'Ecuador', hu: 'Ecuador', sk: 'Ekvádor' } },
      { code: 'gy', name: { en: 'Guyana', es: 'Guyana', de: 'Guyana', pl: 'Gujana', ru: 'Гайана', uk: 'Гаяна', bg: 'Гаяна', ro: 'Guyana', hu: 'Guyana', sk: 'Guyana' } },
      { code: 'py', name: { en: 'Paraguay', es: 'Paraguay', de: 'Paraguay', pl: 'Paragwaj', ru: 'Парагвай', uk: 'Парагвай', bg: 'Парагвай', ro: 'Paraguay', hu: 'Paraguay', sk: 'Paraguaj' } },
      { code: 'pe', name: { en: 'Peru', es: 'Perú', de: 'Peru', pl: 'Peru', ru: 'Перу', uk: 'Перу', bg: 'Перу', ro: 'Peru', hu: 'Peru', sk: 'Peru' } },
      { code: 'sr', name: { en: 'Suriname', es: 'Surinam', de: 'Suriname', pl: 'Surinam', ru: 'Суринам', uk: 'Суринам', bg: 'Суринам', ro: 'Surinam', hu: 'Suriname', sk: 'Surinam' } },
      { code: 'uy', name: { en: 'Uruguay', es: 'Uruguay', de: 'Uruguay', pl: 'Urugwaj', ru: 'Уругвай', uk: 'Уругвай', bg: 'Уругвай', ro: 'Uruguay', hu: 'Uruguay', sk: 'Uruguaj' } },
      { code: 've', name: { en: 'Venezuela', es: 'Venezuela', de: 'Venezuela', pl: 'Wenezuela', ru: 'Венесуэла', uk: 'Венесуела', bg: 'Венецуела', ro: 'Venezuela', hu: 'Venezuela', sk: 'Venezuela' } },
    ],
  },
  {
    id: 'oceania',
    countries: [
      { code: 'au', name: { en: 'Australia', es: 'Australia', de: 'Australien', pl: 'Australia', ru: 'Австралия', uk: 'Австралія', bg: 'Австралия', ro: 'Australia', hu: 'Ausztrália', sk: 'Austrália' } },
      { code: 'fj', name: { en: 'Fiji', es: 'Fiyi', de: 'Fidschi', pl: 'Fidżi', ru: 'Фиджи', uk: 'Фіджі', bg: 'Фиджи', ro: 'Fiji', hu: 'Fidzsi-szigetek', sk: 'Fidži' } },
      { code: 'ki', name: { en: 'Kiribati', es: 'Kiribati', de: 'Kiribati', pl: 'Kiribati', ru: 'Кирибати', uk: 'Кірибаті', bg: 'Кирибати', ro: 'Kiribati', hu: 'Kiribati', sk: 'Kiribati' } },
      { code: 'mh', name: { en: 'Marshall Islands', es: 'Islas Marshall', de: 'Marshallinseln', pl: 'Wyspy Marshalla', ru: 'Маршалловы Острова', uk: 'Маршаллові Острови', bg: 'Маршалови острови', ro: 'Insulele Marshall', hu: 'Marshall-szigetek', sk: 'Marshallove ostrovy' } },
      { code: 'fm', name: { en: 'Micronesia', es: 'Micronesia', de: 'Mikronesien', pl: 'Mikronezja', ru: 'Микронезия', uk: 'Мікронезія', bg: 'Микронезия', ro: 'Micronezia', hu: 'Mikronézia', sk: 'Mikronézia' } },
      { code: 'nr', name: { en: 'Nauru', es: 'Nauru', de: 'Nauru', pl: 'Nauru', ru: 'Науру', uk: 'Науру', bg: 'Науру', ro: 'Nauru', hu: 'Nauru', sk: 'Nauru' } },
      { code: 'nz', name: { en: 'New Zealand', es: 'Nueva Zelanda', de: 'Neuseeland', pl: 'Nowa Zelandia', ru: 'Новая Зеландия', uk: 'Нова Зеландія', bg: 'Нова Зеландия', ro: 'Noua Zeelandă', hu: 'Új-Zéland', sk: 'Nový Zéland' } },
      { code: 'pw', name: { en: 'Palau', es: 'Palaos', de: 'Palau', pl: 'Palau', ru: 'Палау', uk: 'Палау', bg: 'Палау', ro: 'Palau', hu: 'Palau', sk: 'Palau' } },
      { code: 'pg', name: { en: 'Papua New Guinea', es: 'Papúa Nueva Guinea', de: 'Papua-Neuguinea', pl: 'Papua-Nowa Gwinea', ru: 'Папуа — Новая Гвинея', uk: 'Папуа Нова Гвінея', bg: 'Папуа Нова Гвинея', ro: 'Papua Noua Guinee', hu: 'Pápua Új-Guinea', sk: 'Papua-Nová Guinea' } },
      { code: 'ws', name: { en: 'Samoa', es: 'Samoa', de: 'Samoa', pl: 'Samoa', ru: 'Самоа', uk: 'Самоа', bg: 'Самоа', ro: 'Samoa', hu: 'Szamoa', sk: 'Samoa' } },
      { code: 'sb', name: { en: 'Solomon Islands', es: 'Islas Salomón', de: 'Salomonen', pl: 'Wyspy Salomona', ru: 'Соломоновы Острова', uk: 'Соломонові Острови', bg: 'Соломонови острови', ro: 'Insulele Solomon', hu: 'Salamon-szigetek', sk: 'Šalamúnove ostrovy' } },
      { code: 'to', name: { en: 'Tonga', es: 'Tonga', de: 'Tonga', pl: 'Tonga', ru: 'Тонга', uk: 'Тонга', bg: 'Тонга', ro: 'Tonga', hu: 'Tonga', sk: 'Tonga' } },
      { code: 'tv', name: { en: 'Tuvalu', es: 'Tuvalu', de: 'Tuvalu', pl: 'Tuvalu', ru: 'Тувалу', uk: 'Тувалу', bg: 'Тувалу', ro: 'Tuvalu', hu: 'Tuvalu', sk: 'Tuvalu' } },
      { code: 'vu', name: { en: 'Vanuatu', es: 'Vanuatu', de: 'Vanuatu', pl: 'Vanuatu', ru: 'Вануату', uk: 'Вануату', bg: 'Вануату', ro: 'Vanuatu', hu: 'Vanuatu', sk: 'Vanuatu' } },
    ],
  },
];

export function getAllCountries() {
  return continents.flatMap((c) => c.countries);
}

export function getCountryByCode(code) {
  return getAllCountries().find((c) => c.code === code);
}
